name: Build Binary

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build release binary
        run: cargo build --locked --release --bin run_compose

      - name: Package artifact
        run: |
          set -euo pipefail
          mkdir -p bundle
          cp target/release/run_compose bundle/run-compose
          strip bundle/run-compose || true
          cp README.md bundle/README.md
          cp LICENSE bundle/
          mkdir -p bundle/docs
          cp docs/run_compose_cli.md bundle/docs/
          tar -czf run-compose-linux-x86_64.tar.gz -C bundle .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-compose-linux-x86_64
          path: run-compose-linux-x86_64.tar.gz
